name: Deploy to Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build project
      run: |
        mkdir -p build
        echo "Hello, World!" > build/index.html

    - name: Upload files via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: 22
        username: root
        password: Hj1123165691
        source: "build/*"
        target: "/var/www/html"
        debug: true  # 启用调试模式
