name: BUILD v8

on:
  push:
    branches: [ master ]

env:
  PATCH_FLAG: true
  COMMIT: 6dc88c191f5ecc5389dc26efa3ca0907faef3598
  DEPOT_UPLOAD: false
  SRC_UPLOAD: true
  BINARY_UPLOAD: false

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: init env
      run: |
        sudo apt-get update
        sudo apt-get -y install pkg-config git subversion curl wget build-essential python-is-python3 xz-utils zip p7zip-full

    - name: Fix Python 2/3 compatibility
      run: |
        sudo apt-get install python2
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
        sudo update-alternatives --set python /usr/bin/python2

    - name: depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo export PATH=\"\$PATH:`pwd`/depot_tools/\" >> ~/.bash_profile

    - name: fetch v8
      run: |
        source ~/.bash_profile
        fetch v8
        cd v8

    - name: patch v8
      if: env.PATCH_FLAG == 'true' && !cancelled()
      run: |
        cd v8
        echo "Resetting to commit: $COMMIT"
        git reset --hard $COMMIT
        cd ..

    - name: Clean up obsolete directories
      run: |
        cd v8
        rm -rf third_party/zlib third_party/re2/src third_party/logdog/logdog
        cd ..

    - name: build v8
      run: |
        source ~/.bash_profile
        echo "Running gclient sync -f"
        gclient sync -f

    - name: zip depot_tools
      if: env.DEPOT_UPLOAD == 'true' && !cancelled()
      run: |
        echo "Compressing depot_tools..."
        zip -q -r depot_tools.zip depot_tools

    - name: 7zip v8_src
      run: |
        echo "Compressing v8 source code..."
        zip -q -r v8.zip v8
        7z a v8.7z ./v8.zip -v2048m

    - name: upload depot_tools
      if: env.DEPOT_UPLOAD == 'true' && !cancelled()
      run: |
        echo "Uploading depot_tools.zip..."
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress depot_tools.zip 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"

    - name: upload v8_src
      if: env.SRC_UPLOAD == 'true' && !cancelled()
      run: |
        echo "Uploading v8.7z.001..."
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress v8.7z.001 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        echo "Uploading v8.7z.002..."
        ./transfer cow --block 2621440 -s -p 64 --no-progress v8.7z.002 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
