name: Check Disk Space

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check disk space
      run: df -h

    - name: Check /tmp disk space
      run: df -h /tmp

    - name: Clean up /tmp
      run: sudo rm -rf /tmp/*
